/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PhysiotherapistRole;

import userinterface.PhysiotherapistRole.*;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Customer.Customer;
import Business.Employee.Employee;
import Business.Organization.Organization;

import Business.Organization.PhysioOrganization;
import Business.UserAccount.UserAccount;

import Business.WorkQueue.PhysioWorkRequest;
import Business.WorkQueue.WorkRequest;
import Business.utilities.tableHeaderColors;
import java.io.IOException;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Multipart;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aishwaryasamel
 */
public class PhysioWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PhysioWorkAreaJPanel
     */
    JPanel userProcessContainer;
    UserAccount account;
    Enterprise enterprise;
    EcoSystem ecosystem;
    Network network;

    public PhysioWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise, Organization organization, UserAccount account, EcoSystem business, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
         this.account = account;
         this.enterprise = enterprise;
         this.ecosystem = business;
         this.network = network;
         populateCustomer();
         greetLbl.setText(account.getEmployee().getName() + "!!");
        tblCustomerList.getTableHeader().setDefaultRenderer(new tableHeaderColors());
        
    }
    
    public void populateCustomer(){
        DefaultTableModel dtm = (DefaultTableModel) tblCustomerList.getModel();
        dtm.setRowCount(0);
        
        for(Organization org: enterprise.getOrganizationDirectory().getOrganizationList()){
        for(Employee emp : org.getEmployeeDirectory().getEmployeeList()){
            if(emp.toString().equals(account.getEmployee().toString())){
                for( WorkRequest request: account.getWorkQueue().getWorkRequestList()){
                Customer cust = request.getSender().getCustomer();
            
            Object[] row = new Object[4];
            row[0] = cust.getId();
            row[1] = cust;
            row[2] = request;
            row[3] = request.getStatus();
            dtm.addRow(row);
           }
            }
        }
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCustomerList = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        radioMale = new javax.swing.JRadioButton();
        radioFemale = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        txtHeight = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtWeight = new javax.swing.JTextField();
        hyperCheckBox = new javax.swing.JCheckBox();
        noneCheckBox = new javax.swing.JCheckBox();
        diabCheckBox = new javax.swing.JCheckBox();
        pcosCheckBox = new javax.swing.JCheckBox();
        thyroidCheckBox = new javax.swing.JCheckBox();
        cholestrolCheckBox = new javax.swing.JCheckBox();
        jLabel16 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        greetLbl = new javax.swing.JLabel();
        viewDetailsBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        physioMsgTxt = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblCustomerList.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        tblCustomerList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Customer ID", "Customer Name", "Goal", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCustomerList);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 112, 675, 91));

        jButton1.setBackground(new java.awt.Color(255, 102, 0));
        jButton1.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jButton1.setText("Process Request");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 630, -1, 40));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 107, 30));

        nameTxt.setEditable(false);
        nameTxt.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        add(nameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 190, 30));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Age:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 90, 30));

        txtAge.setEditable(false);
        add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 190, 30));

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Gender:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 107, 40));

        radioMale.setBackground(new java.awt.Color(204, 204, 255));
        radioMale.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        radioMale.setText("Male");
        radioMale.setEnabled(false);
        radioMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMaleActionPerformed(evt);
            }
        });
        add(radioMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, 68, -1));

        radioFemale.setBackground(new java.awt.Color(204, 204, 255));
        radioFemale.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        radioFemale.setText("Female");
        radioFemale.setEnabled(false);
        radioFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioFemaleActionPerformed(evt);
            }
        });
        add(radioFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, 72, -1));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Height(in cms):");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 86, 30));

        txtHeight.setEditable(false);
        add(txtHeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, 190, 30));

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Weight (in Kgs):");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 470, -1, 30));

        txtWeight.setEditable(false);
        add(txtWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 470, 190, 30));

        hyperCheckBox.setBackground(new java.awt.Color(204, 204, 255));
        hyperCheckBox.setText("Hypertension");
        hyperCheckBox.setEnabled(false);
        hyperCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hyperCheckBoxActionPerformed(evt);
            }
        });
        add(hyperCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 400, -1, -1));

        noneCheckBox.setBackground(new java.awt.Color(204, 204, 255));
        noneCheckBox.setText("None");
        noneCheckBox.setEnabled(false);
        add(noneCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 360, 90, -1));

        diabCheckBox.setBackground(new java.awt.Color(204, 204, 255));
        diabCheckBox.setText("Diabetes");
        diabCheckBox.setEnabled(false);
        add(diabCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 360, 90, -1));

        pcosCheckBox.setBackground(new java.awt.Color(204, 204, 255));
        pcosCheckBox.setText("PCOS");
        pcosCheckBox.setEnabled(false);
        add(pcosCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 400, 90, -1));

        thyroidCheckBox.setBackground(new java.awt.Color(204, 204, 255));
        thyroidCheckBox.setText("Thyroid");
        thyroidCheckBox.setEnabled(false);
        add(thyroidCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 400, 90, -1));

        cholestrolCheckBox.setBackground(new java.awt.Color(204, 204, 255));
        cholestrolCheckBox.setText("Cholestrol");
        cholestrolCheckBox.setEnabled(false);
        add(cholestrolCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 360, 90, -1));

        jLabel16.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(80, 80, 82));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Health Issues");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 330, 310, -1));

        jPanel3.setBackground(new java.awt.Color(102, 153, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Welcome,");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, -40, 120, 140));

        greetLbl.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        greetLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel3.add(greetLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, -50, 320, 160));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 60));

        viewDetailsBtn.setBackground(new java.awt.Color(255, 102, 0));
        viewDetailsBtn.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        viewDetailsBtn.setText("View Details");
        viewDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDetailsBtnActionPerformed(evt);
            }
        });
        add(viewDetailsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, 138, 45));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(80, 80, 82));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CUSTOMER DETAILS");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1209, 39));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Message:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 550, 100, -1));

        physioMsgTxt.setColumns(20);
        physioMsgTxt.setRows(5);
        jScrollPane2.setViewportView(physioMsgTxt);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 520, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/images/customerPhysio.png"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 950, 660));
    }// </editor-fold>//GEN-END:initComponents

    private void radioMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMaleActionPerformed
        radioFemale.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_radioMaleActionPerformed

    private void radioFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioFemaleActionPerformed
        radioMale.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_radioFemaleActionPerformed

    private void hyperCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hyperCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hyperCheckBoxActionPerformed

    private void viewDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDetailsBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblCustomerList.getSelectedRow();
        if(selectedRow >=0){
            Customer customer = (Customer) tblCustomerList.getValueAt(selectedRow, 1);
            nameTxt.setText(customer.getName());
            txtAge.setText(String.valueOf(customer.getAge()));
            if(customer.getGender().toLowerCase().equals("male")){
                radioMale.setSelected(true);
            }else{
                radioFemale.setSelected(false);
            }
            txtHeight.setText(String.valueOf(customer.getHeight()));
            txtWeight.setText(String.valueOf(customer.getWeight()));
            noneCheckBox.setSelected(customer.getNone());
            diabCheckBox.setSelected(customer.getDiabetes());
            cholestrolCheckBox.setSelected(customer.getCholestrol());
            hyperCheckBox.setSelected(customer.getHypertension());
            pcosCheckBox.setSelected(customer.getPcos());
            thyroidCheckBox.setSelected(customer.getThyroid());
        }else{
            JOptionPane.showMessageDialog(null,"Please Select a row","Error",JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_viewDetailsBtnActionPerformed

   public void sendEmail(String email, String name){
                //final String username = "";
		final String password = "HealthifyMe123#";
		String fromEmail = "healthifyyme@gmail.com";
		//String toEmail = "surprise.aishwarya@gmail.com";
		String toEmail = email;
		Properties properties = new Properties();
		properties.put("mail.smtp.auth", "true");
                properties.put("mail.smtp.ssl.trust", "smtp.gmail.com");
		properties.put("mail.smtp.starttls.enable", "true");
		properties.put("mail.smtp.host", "smtp.gmail.com");
		properties.put("mail.smtp.port", "587");
		
		Session session = Session.getInstance(properties, new javax.mail.Authenticator() {
			protected PasswordAuthentication getPasswordAuthentication() {
				return new PasswordAuthentication(fromEmail,password);
			}
		});
		//Start our mail message
		MimeMessage msg = new MimeMessage(session);
		try {
			msg.setFrom(new InternetAddress(fromEmail));
			msg.addRecipient(Message.RecipientType.TO, new InternetAddress(toEmail));
			msg.setSubject("Physiotherapist - "+name+"'s"+" Zoom Link");
			
			Multipart emailContent = new MimeMultipart();
			
			//Text body part
			MimeBodyPart textBodyPart = new MimeBodyPart();
			textBodyPart.setText("Please find the attached Zoom link");
                        
                        MimeBodyPart textBodyPart2 = new MimeBodyPart();
			textBodyPart2.setText("https://northeastern.zoom.us/j/6735568010/"+ name+"/");
			
			//Attachment body part.
			
//			
			//Attach body parts
			emailContent.addBodyPart(textBodyPart);
                        emailContent.addBodyPart(textBodyPart2);
			
			
			//Attach multipart to message
			msg.setContent(emailContent);
			
			Transport.send(msg);
			System.out.println("Sent message");
		}catch (MessagingException e) {
			e.printStackTrace();
		}
        // TODO Auto-generated catch block
         

    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int selectedRow = tblCustomerList.getSelectedRow();
        if(selectedRow >=0){
            PhysioWorkRequest request = (PhysioWorkRequest) tblCustomerList.getValueAt(selectedRow, 2);
            if(!"Result Posted".equals(request.getStatus())){
                request.setStatus("Result Posted");
                request.setPhysioResult(physioMsgTxt.getText());
                String email = request.getSender().getUsername();
                String name = account.getEmployee().getName();
                sendEmail(email, name);
                populateCustomer();
                JOptionPane.showMessageDialog(null,"Email has been sent to Customer!","Success",JOptionPane.INFORMATION_MESSAGE);
                physioMsgTxt.setText("");
            }else{
                JOptionPane.showMessageDialog(null,"Result has been already Processed","INFORMATION",JOptionPane.INFORMATION_MESSAGE);
            }
            
        }else{
            JOptionPane.showMessageDialog(null,"Please Select a row","Error",JOptionPane.ERROR_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cholestrolCheckBox;
    private javax.swing.JCheckBox diabCheckBox;
    private javax.swing.JLabel greetLbl;
    private javax.swing.JCheckBox hyperCheckBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JCheckBox noneCheckBox;
    private javax.swing.JCheckBox pcosCheckBox;
    private javax.swing.JTextArea physioMsgTxt;
    private javax.swing.JRadioButton radioFemale;
    private javax.swing.JRadioButton radioMale;
    private javax.swing.JTable tblCustomerList;
    private javax.swing.JCheckBox thyroidCheckBox;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtWeight;
    private javax.swing.JButton viewDetailsBtn;
    // End of variables declaration//GEN-END:variables
}
