/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AdministrativeRole;

import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.Organization.Type;
import Business.Organization.OrganizationDirectory;
import Business.utilities.tableHeaderColors;
import java.awt.CardLayout;
import java.time.Clock;
import static java.time.Clock.system;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author risha
 */
public class ManageOrganizationJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    
    /**
     * Creates new form ManageOrganizationJPanel
     */
    public ManageOrganizationJPanel(JPanel userProcessContainer,Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        organizationJTable.getTableHeader().setDefaultRenderer(new tableHeaderColors());
        populateTable();
        populateCombo();
    }
    
    private void populateCombo(){
        organizationJComboBox.removeAllItems();
        String ent = enterprise.getEnterpriseType().toString();
         for (Type type : Organization.Type.values()){
            if(ent.equals("Diet Unit")){
                 if (type.getValue().equals(Type.Nutrition.getValue())){
                    organizationJComboBox.addItem(type);
                }
            }else if(ent.equals("Trainer Unit")){
                 if (type.getValue().equals(Type.FitnessTraining.getValue())){
                    organizationJComboBox.addItem(type);
                }
                if (type.getValue().equals(Type.WeightTraining.getValue())){
                    organizationJComboBox.addItem(type);
                }
                 
            }
            else if(ent.equals("Doctor Unit")){
                 if (type.getValue().equals(Type.GeneralPractitioner.getValue())){
                    organizationJComboBox.addItem(type);
                }
                if (type.getValue().equals(Type.Physiotherapist.getValue())){
                    organizationJComboBox.addItem(type);
                }
                if (type.getValue().equals(Type.Orthopedic.getValue())){
                    organizationJComboBox.addItem(type);
                }
                 
            }
            else if(ent.equals("Store Unit")){
                 if (type.getValue().equals(Type.Store.getValue())){
                    organizationJComboBox.addItem(type);
                }
                if (type.getValue().equals(Type.Delivery.getValue())){
                    organizationJComboBox.addItem(type);
                } 
            }
         }
    }

    private void populateTable(){
        DefaultTableModel model = (DefaultTableModel) organizationJTable.getModel();
        
        model.setRowCount(0);
        //System.out.println(Network);
        
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            Object[] row = new Object[2];
            row[0] = organization.getOrganizationID();
            row[1] = organization.getName();
            
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        organizationJTable = new javax.swing.JTable();
        addJButton = new javax.swing.JButton();
        organizationJComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(238, 137, 19));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        organizationJTable.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        organizationJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(organizationJTable);
        if (organizationJTable.getColumnModel().getColumnCount() > 0) {
            organizationJTable.getColumnModel().getColumn(0).setResizable(false);
            organizationJTable.getColumnModel().getColumn(1).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 91, 480, 92));

        addJButton.setBackground(new java.awt.Color(255, 102, 0));
        addJButton.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        addJButton.setText("Add");
        addJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJButtonActionPerformed(evt);
            }
        });
        add(addJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 303, 122, 42));

        organizationJComboBox.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        organizationJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        organizationJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizationJComboBoxActionPerformed(evt);
            }
        });
        add(organizationJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 223, 190, 30));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel1.setText("Organization Type :");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 231, -1, -1));

        backJButton.setBackground(new java.awt.Color(255, 102, 0));
        backJButton.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, -1, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/images/manageaOrg.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 640));
    }// </editor-fold>//GEN-END:initComponents

    private void addJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJButtonActionPerformed

        Type type = (Type) organizationJComboBox.getSelectedItem();
        String t = String.valueOf(type)+" Organization";
        for(Organization org: enterprise.getOrganizationDirectory().getOrganizationList()){   
            if(org.getName().equals(t)){
                JOptionPane.showMessageDialog(null, "Organization is already added !","Alert",JOptionPane.INFORMATION_MESSAGE);
                return;
            }
        }
        enterprise.getOrganizationDirectory().createOrganization(type);
        populateTable();
        
        
        // COMMENTED TO CHECK ORG
         /*Type type = (Type) organizationJComboBox.getSelectedItem();
       Object[] columnData = new Object[organizationJTable.getRowCount()];
            Object[] rowData = new Object [organizationJTable.getRowCount()];
            if(organizationJTable.getRowCount() > 0){
            for (int i = 0; i < organizationJTable.getRowCount(); i++) {  
                columnData[i] = organizationJTable.getValueAt(i, 1);
                if(!columnData[i].equals(type.getValue())){
                     enterprise.getOrganizationDirectory().createOrganization(type);
                     orgPresent = 1;
                     populateTable();
                }else {
                    orgPresent = 0;
                }
             }
            }else{
                    enterprise.getOrganizationDirectory().createOrganization(type);
                     populateTable();
                     orgPresent = 1;
            }
            
            if(orgPresent == 0){
                JOptionPane.showMessageDialog(null,"Organization is already Present","Alert",JOptionPane.WARNING_MESSAGE);
                return;
            }*/
    }//GEN-LAST:event_addJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void organizationJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizationJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_organizationJComboBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox organizationJComboBox;
    private javax.swing.JTable organizationJTable;
    // End of variables declaration//GEN-END:variables
}
