/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerRole;

import Business.Customer.Customer;
import userinterface.SystemAdminWorkArea.*;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Role.CustomerRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author risha
 */
public class CreateNewCustomerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateNewCustomerJPanel
     */
    JPanel userProcessContainer;
    EcoSystem system;
    Organization organization;
     private Customer c;
     private boolean ageValid;
     private boolean emailValid;
     private boolean zipValid;
     private boolean heightValid;
     private boolean weightValid;
     private boolean cityValid;
    public CreateNewCustomerJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.system=system;
        this.organization = organization;
        clearLabels();
        populateNetworkComboBox();
        
    }
    private void clearLabels(){
     // Labels initialzed to false
        nameLbl.setVisible(false);
        nameSuccessLbl.setVisible(false);
        emailLbl.setVisible(false);
         emailIDAlreadyLbl.setVisible(false);
        emailSuccessLbl.setVisible(false);
        passwordSuccessLbl.setVisible(false);
        passwordLbl.setVisible(false);
        confirmPasswordSuccessLbl.setVisible(false);
        confirmPasswordLbl.setVisible(false);
        AgeSuccessLbl.setVisible(false);
        invalidAgeLbl.setVisible(false);
        ageBandLbl.setVisible(false);
        addressSuccessLbl.setVisible(false);
        addressLbl.setVisible(false);
        cityLbl.setVisible(false);
        citySuccessLbl.setVisible(false);
        zipLbl.setVisible(false);
        zipSuccessLbl.setVisible(false);
        heightLbl.setVisible(false);
        heightSuccessLbl.setVisible(false);
        weightLbl.setVisible(false);
        weightSuccessLbl.setVisible(false);
    
    }
private void populateNetworkComboBox() {
        networkJComboBox.removeAllItems();

        for (Network network : system.getNetworkList()) {
            networkJComboBox.addItem(network);
        }

    }
    
    private boolean usernamePatternCorrect(String val){
        Pattern p=Pattern.compile("^[a-zA-Z0-9]+@[a-zA-Z0-9]+.[a-zA-Z0-9]+$");
        Matcher m=p.matcher(val);
        boolean b=m.matches();
        return b;
    }
    private boolean namePatternCorrect(String val1){
        Pattern p=Pattern.compile("^[a-zA-Z]+$");
        Matcher m=p.matcher(val1);
        boolean b=m.matches();
        return b;
    }
    private boolean addressPatternCorrect(String val2){
        Pattern p=Pattern.compile("^[a-z A-Z 0-9#/-]+$");
        Matcher m=p.matcher(val2);
        boolean b=m.matches();
        return b;
    }
    private boolean cityPatternCorrect(String val3){
        Pattern p=Pattern.compile("^[a-zA-Z]+$");
        Matcher m=p.matcher(val3);
        boolean b=m.matches();
        return b;
    }
    
    private boolean passwordPatternCorrect(String val4){
        Pattern p1;
        p1 = Pattern.compile("^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{6,}$");
        Matcher m1=p1.matcher(String.valueOf(val4));
        boolean b1=m1.matches();
        return b1;
    }
    private boolean numberPatternCorrect(String val5){
        Pattern p=Pattern.compile("^[0-9]$");
        Matcher m=p.matcher(val5);
        boolean b=m.matches();
        return b;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtName = new javax.swing.JTextField();
        confirmPasswordTxt = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        txtEmail = new javax.swing.JTextField();
        submitBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        resetBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        radioMale = new javax.swing.JRadioButton();
        txtHeight = new javax.swing.JTextField();
        radioFemale = new javax.swing.JRadioButton();
        txtWeight = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtAdress = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        networkJComboBox = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        txtZipcode = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        thyroidChkBox = new javax.swing.JCheckBox();
        noneChkBox = new javax.swing.JCheckBox();
        diabetesChkBox = new javax.swing.JCheckBox();
        cholestrolChkBox = new javax.swing.JCheckBox();
        hyperChkBox = new javax.swing.JCheckBox();
        pcosChkBox = new javax.swing.JCheckBox();
        jLabel17 = new javax.swing.JLabel();
        AgeSuccessLbl = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        invalidAgeLbl = new javax.swing.JLabel();
        ageBandLbl = new javax.swing.JLabel();
        confirmPasswordSuccessLbl = new javax.swing.JLabel();
        confirmPasswordLbl = new javax.swing.JLabel();
        nameSuccessLbl = new javax.swing.JLabel();
        emailLbl = new javax.swing.JLabel();
        emailSuccessLbl = new javax.swing.JLabel();
        passwordSuccessLbl = new javax.swing.JLabel();
        passwordLbl = new javax.swing.JLabel();
        addressLbl = new javax.swing.JLabel();
        addressSuccessLbl = new javax.swing.JLabel();
        citySuccessLbl = new javax.swing.JLabel();
        cityLbl = new javax.swing.JLabel();
        zipSuccessLbl = new javax.swing.JLabel();
        zipLbl = new javax.swing.JLabel();
        weightSuccessLbl = new javax.swing.JLabel();
        heightSuccessLbl = new javax.swing.JLabel();
        weightLbl = new javax.swing.JLabel();
        heightLbl = new javax.swing.JLabel();
        emailIDAlreadyLbl = new javax.swing.JLabel();
        bgLbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(238, 137, 19));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtName.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNameKeyReleased(evt);
            }
        });
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 190, 30));

        confirmPasswordTxt.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        confirmPasswordTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                confirmPasswordTxtKeyReleased(evt);
            }
        });
        add(confirmPasswordTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 190, 30));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Email ID:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 107, 30));

        txtPassword.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPasswordKeyReleased(evt);
            }
        });
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 190, 30));

        txtEmail.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailKeyReleased(evt);
            }
        });
        add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 190, 30));

        submitBtn.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });
        add(submitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 530, 100, 50));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Password:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 107, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(80, 80, 82));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CUSTOMER REGISTRATION");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-110, 10, 1210, 50));

        resetBtn.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });
        add(resetBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 530, 100, 50));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 107, 30));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Confirm Password:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, -1, 30));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Age:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 90, 30));

        txtAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAgeKeyReleased(evt);
            }
        });
        add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, 190, 30));

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Gender:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 107, 20));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Height(in cms):");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 86, 30));

        radioMale.setBackground(new java.awt.Color(255, 255, 255));
        radioMale.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        radioMale.setSelected(true);
        radioMale.setText("Male");
        radioMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMaleActionPerformed(evt);
            }
        });
        add(radioMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 68, -1));

        txtHeight.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtHeightKeyReleased(evt);
            }
        });
        add(txtHeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, 190, 30));

        radioFemale.setBackground(new java.awt.Color(255, 255, 255));
        radioFemale.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        radioFemale.setText("Female");
        radioFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioFemaleActionPerformed(evt);
            }
        });
        add(radioFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 72, -1));

        txtWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWeightActionPerformed(evt);
            }
        });
        txtWeight.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtWeightKeyReleased(evt);
            }
        });
        add(txtWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, 190, 30));

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Address:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 110, 30));

        txtAdress.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        txtAdress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAdressKeyReleased(evt);
            }
        });
        add(txtAdress, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, 190, 30));

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("City:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 90, 30));

        txtCity.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        txtCity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCityKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCityKeyReleased(evt);
            }
        });
        add(txtCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 210, 190, 30));

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("State:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, 80, 30));

        networkJComboBox.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        networkJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(networkJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 260, 190, 30));

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Zip Code:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, 110, 30));

        txtZipcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtZipcodeKeyReleased(evt);
            }
        });
        add(txtZipcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 310, 190, 30));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 1190, 10));

        jLabel16.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(80, 80, 82));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Health Issues");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, 310, -1));

        thyroidChkBox.setBackground(new java.awt.Color(204, 204, 204));
        thyroidChkBox.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        thyroidChkBox.setText("Thyroid");
        thyroidChkBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                thyroidChkBoxMousePressed(evt);
            }
        });
        add(thyroidChkBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 470, 90, -1));

        noneChkBox.setBackground(new java.awt.Color(204, 204, 204));
        noneChkBox.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        noneChkBox.setText("None");
        noneChkBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                noneChkBoxMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                noneChkBoxMousePressed(evt);
            }
        });
        add(noneChkBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 430, 90, -1));

        diabetesChkBox.setBackground(new java.awt.Color(204, 204, 204));
        diabetesChkBox.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        diabetesChkBox.setText("Diabetes");
        diabetesChkBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                diabetesChkBoxMousePressed(evt);
            }
        });
        add(diabetesChkBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 430, 90, -1));

        cholestrolChkBox.setBackground(new java.awt.Color(204, 204, 204));
        cholestrolChkBox.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        cholestrolChkBox.setText("Cholestrol");
        cholestrolChkBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cholestrolChkBoxMousePressed(evt);
            }
        });
        add(cholestrolChkBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 430, 90, -1));

        hyperChkBox.setBackground(new java.awt.Color(204, 204, 204));
        hyperChkBox.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        hyperChkBox.setText("Hypertension");
        hyperChkBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                hyperChkBoxMousePressed(evt);
            }
        });
        hyperChkBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hyperChkBoxActionPerformed(evt);
            }
        });
        add(hyperChkBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 470, 100, -1));

        pcosChkBox.setBackground(new java.awt.Color(204, 204, 204));
        pcosChkBox.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        pcosChkBox.setText("PCOS");
        pcosChkBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pcosChkBoxMousePressed(evt);
            }
        });
        add(pcosChkBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 470, 90, -1));

        jLabel17.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Weight (in Kgs):");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 465, -1, 20));

        AgeSuccessLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/images/tick.png"))); // NOI18N
        add(AgeSuccessLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 104, 50, 40));

        nameLbl.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        nameLbl.setForeground(new java.awt.Color(255, 0, 0));
        nameLbl.setText(" Only Alphabets are allowed.");
        add(nameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 190, 20));

        invalidAgeLbl.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        invalidAgeLbl.setForeground(new java.awt.Color(255, 0, 0));
        invalidAgeLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        invalidAgeLbl.setText("Invalid Age.");
        add(invalidAgeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, 190, 20));

        ageBandLbl.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        ageBandLbl.setForeground(new java.awt.Color(255, 0, 0));
        ageBandLbl.setText("Age Should be between 15-85");
        add(ageBandLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, -1, 20));

        confirmPasswordSuccessLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/images/tick.png"))); // NOI18N
        add(confirmPasswordSuccessLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, 40, -1));

        confirmPasswordLbl.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        confirmPasswordLbl.setForeground(new java.awt.Color(255, 0, 0));
        confirmPasswordLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        confirmPasswordLbl.setText("Password Not Matching");
        add(confirmPasswordLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 160, 20));

        nameSuccessLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/images/tick.png"))); // NOI18N
        add(nameSuccessLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 104, 30, 40));

        emailLbl.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        emailLbl.setForeground(new java.awt.Color(255, 0, 0));
        emailLbl.setText("Valid Format - 'xx@xx.xx'");
        add(emailLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 150, 20));

        emailSuccessLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/images/tick.png"))); // NOI18N
        add(emailSuccessLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 40, 30));

        passwordSuccessLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/images/tick.png"))); // NOI18N
        add(passwordSuccessLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 30, -1));

        passwordLbl.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        passwordLbl.setForeground(new java.awt.Color(255, 0, 0));
        passwordLbl.setText("Sample format: Asdf@1");
        add(passwordLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 160, 20));

        addressLbl.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        addressLbl.setForeground(new java.awt.Color(255, 0, 0));
        addressLbl.setText("Only Alphabets, Numbers, '#/-' are allowed");
        add(addressLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, 250, 20));

        addressSuccessLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/images/tick.png"))); // NOI18N
        add(addressSuccessLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 160, 50, -1));

        citySuccessLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/images/tick.png"))); // NOI18N
        add(citySuccessLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 210, 30, -1));

        cityLbl.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        cityLbl.setForeground(new java.awt.Color(255, 0, 0));
        cityLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cityLbl.setText("Only Alphabets are allowed");
        add(cityLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 240, 160, 20));

        zipSuccessLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/images/tick.png"))); // NOI18N
        add(zipSuccessLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 310, 30, -1));

        zipLbl.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        zipLbl.setForeground(new java.awt.Color(255, 0, 0));
        zipLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        zipLbl.setText("Only Numbers Allowed");
        add(zipLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 340, 160, 20));

        weightSuccessLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/images/tick.png"))); // NOI18N
        add(weightSuccessLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 460, 40, 30));

        heightSuccessLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        heightSuccessLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/images/tick.png"))); // NOI18N
        add(heightSuccessLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 410, 60, 30));

        weightLbl.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        weightLbl.setForeground(new java.awt.Color(255, 0, 0));
        weightLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        weightLbl.setText("Invalid Weight");
        add(weightLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 490, 160, 20));

        heightLbl.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        heightLbl.setForeground(new java.awt.Color(255, 0, 0));
        heightLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        heightLbl.setText("Invalid Height");
        add(heightLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, 160, 20));

        emailIDAlreadyLbl.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        emailIDAlreadyLbl.setForeground(new java.awt.Color(255, 0, 0));
        emailIDAlreadyLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emailIDAlreadyLbl.setText("EmailID already Exists");
        add(emailIDAlreadyLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 160, 20));

        bgLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/images/customerRegistration.png"))); // NOI18N
        add(bgLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 1240, 790));
    }// </editor-fold>//GEN-END:initComponents

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        clearValues();
        clearLabels();
        // TODO add your handling code here:
    }//GEN-LAST:event_resetBtnActionPerformed
        private void clearValues(){
                txtName.setText("");
                txtEmail.setText("");
                txtPassword.setText("");
                confirmPasswordTxt.setText("");
                txtAge.setText("");
                txtAdress.setText("");
                txtCity.setText("");
                try{
                networkJComboBox.setSelectedIndex(0);
                }catch (Exception e){
                    
                }
                txtZipcode.setText("");
                txtHeight.setText("");
                txtWeight.setText("");
                 diabetesChkBox.setSelected(false);
                cholestrolChkBox.setSelected(false);
                hyperChkBox.setSelected(false);
                pcosChkBox.setSelected(false);
                thyroidChkBox.setSelected(false);
                noneChkBox.setSelected(false);
                nameSuccessLbl.setVisible(false);
                emailSuccessLbl.setVisible(false);
                passwordSuccessLbl.setVisible(false);
                confirmPasswordSuccessLbl.setVisible(false);
                AgeSuccessLbl.setVisible(false);
                addressSuccessLbl.setVisible(false);
                citySuccessLbl.setVisible(false);
                zipSuccessLbl.setVisible(false);
                heightSuccessLbl.setVisible(false);
                weightSuccessLbl.setVisible(false);
        }
    /* public void populateLongituteLatitude(LatLong latLong) {
        this.latLong = latLong;
        latLongTxt.setText(latLong.getLat()+ "," + latLong.getLongi());
    }*/
    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        Network network = (Network) networkJComboBox.getSelectedItem();
         if(txtName.getText().isEmpty() || txtAge.getText().isEmpty() || txtWeight.getText().isEmpty() || txtHeight.getText().isEmpty() || txtEmail.getText().isEmpty() || txtAdress.getText().isEmpty() || txtCity.getText().isEmpty() ||  txtZipcode.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Field(s) cannot be Empty!","Error",JOptionPane.ERROR_MESSAGE);
             return;
          }else if(!noneChkBox.isSelected() && !diabetesChkBox.isSelected() && !cholestrolChkBox.isSelected() && !hyperChkBox.isSelected() && !pcosChkBox.isSelected() && !thyroidChkBox.isSelected()){
              JOptionPane.showMessageDialog(null,"Please Fill the Health Issues! If you don't have any kindly Select None!","Error",JOptionPane.ERROR_MESSAGE);
             return;
          
          }else if(ageValid && zipValid && heightValid && weightValid && emailValid){
            String name = txtName.getText();
            String password = txtPassword.getText();
            String email = txtEmail.getText();
            String add = txtAdress.getText();
            String city = txtCity.getText();
            String gender="";
            if(radioMale.isSelected()){
                gender = "Male";
            }else{
                gender = "Female";
            }

            c = new Customer();
            c.setName(name);
            c.setEmail(email);
            c.setHeight(Integer.parseInt(txtHeight.getText()));
            c.setWeight(Integer.parseInt(txtWeight.getText()));
            c.setGender(gender);
            c.setAge(Integer.parseInt(txtAge.getText()));
            c.setAddress(add);
            c.setCity(city);
            c.setZipcode(txtZipcode.getText());
            c.setNone(noneChkBox.isSelected());
            c.setDiabetes(diabetesChkBox.isSelected());
            c.setCholestrol(cholestrolChkBox.isSelected());
            c.setHypertension(hyperChkBox.isSelected());
            c.setPcos(pcosChkBox.isSelected());
            c.setThyroid(thyroidChkBox.isSelected());
            c.setNetwork(network);
            
            // User Name Already Exists Validation 
            
                system.getCustomerDirectory().createCustomer(c);
                system.getUserAccountDirectory().createCustomerAccount(email, password,c, new CustomerRole());
                JOptionPane.showMessageDialog(null, "Customer added successfully","Success",JOptionPane.INFORMATION_MESSAGE);
                clearValues();
                
        }else {
           JOptionPane.showMessageDialog(null, "Please enter all the required fields correctly!","Error",JOptionPane.ERROR_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_submitBtnActionPerformed

    private void radioMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMaleActionPerformed
       // radioFemale.setEnabled(false);
       radioFemale.setSelected(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_radioMaleActionPerformed

    private void radioFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioFemaleActionPerformed
      //  radioMale.setEnabled(false);
        radioMale.setSelected(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_radioFemaleActionPerformed

    private void hyperChkBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hyperChkBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hyperChkBoxActionPerformed

    private void noneChkBoxMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noneChkBoxMousePressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_noneChkBoxMousePressed

    private void diabetesChkBoxMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_diabetesChkBoxMousePressed
        // TODO add your handling code here:
        noneChkBox.setSelected(false);
    }//GEN-LAST:event_diabetesChkBoxMousePressed

    private void noneChkBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noneChkBoxMouseClicked
        // TODO add your handling code here:
        diabetesChkBox.setSelected(false);
        cholestrolChkBox.setSelected(false);
        hyperChkBox.setSelected(false);
        pcosChkBox.setSelected(false);
        thyroidChkBox.setSelected(false);
    }//GEN-LAST:event_noneChkBoxMouseClicked

    private void cholestrolChkBoxMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cholestrolChkBoxMousePressed
        // TODO add your handling code here:
         noneChkBox.setSelected(false);
    }//GEN-LAST:event_cholestrolChkBoxMousePressed

    private void hyperChkBoxMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hyperChkBoxMousePressed
        // TODO add your handling code here:
         noneChkBox.setSelected(false);
    }//GEN-LAST:event_hyperChkBoxMousePressed

    private void pcosChkBoxMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pcosChkBoxMousePressed
        // TODO add your handling code here:
         noneChkBox.setSelected(false);
    }//GEN-LAST:event_pcosChkBoxMousePressed

    private void thyroidChkBoxMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thyroidChkBoxMousePressed
        // TODO add your handling code here:
         noneChkBox.setSelected(false);
    }//GEN-LAST:event_thyroidChkBoxMousePressed

    private void confirmPasswordTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_confirmPasswordTxtKeyReleased
        // TODO add your handling code here:
        if(confirmPasswordTxt.getText().equals(txtPassword.getText()) && !confirmPasswordTxt.getText().isEmpty()){
            confirmPasswordSuccessLbl.setVisible(true);
            confirmPasswordLbl.setVisible(false);
        }else if(confirmPasswordTxt.getText().isEmpty()){
            confirmPasswordLbl.setVisible(false);
             confirmPasswordSuccessLbl.setVisible(false);
        }else{
            confirmPasswordLbl.setVisible(true);
            confirmPasswordSuccessLbl.setVisible(false);
        }
    }//GEN-LAST:event_confirmPasswordTxtKeyReleased

    private void txtAgeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgeKeyReleased
        // TODO add your handling code here:
         // Age As Number
        int age=0;
        try{
            age = Integer.parseInt(txtAge.getText());
        }catch(NumberFormatException e){
            if(!txtAge.getText().isEmpty()){
             invalidAgeLbl.setVisible(true);
             ageValid = false;
             ageBandLbl.setVisible(false);
             AgeSuccessLbl.setVisible(false);
             return;
            }else {
                invalidAgeLbl.setVisible(false);
             ageValid = false;
             ageBandLbl.setVisible(false);
             AgeSuccessLbl.setVisible(false);
             return;
            }
        }
        if(age < 15 || age > 85){
            ageBandLbl.setVisible(true);
            ageValid = false;
             invalidAgeLbl.setVisible(false);
            AgeSuccessLbl.setVisible(false);
        }else{
            invalidAgeLbl.setVisible(false);
            ageBandLbl.setVisible(false);
            ageValid = true;
            AgeSuccessLbl.setVisible(true);
        }
    }//GEN-LAST:event_txtAgeKeyReleased

    private void txtNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyReleased
        // TODO add your handling code here:
        if (!namePatternCorrect(txtName.getText()) && !(txtName.getText().isEmpty())){
              nameLbl.setVisible(true);
              nameSuccessLbl.setVisible(false);
        }else if(txtName.getText().isEmpty()){
            nameLbl.setVisible(false);
             nameSuccessLbl.setVisible(false);
        }else{
         nameLbl.setVisible(false);
         nameSuccessLbl.setVisible(true);
        }
    }//GEN-LAST:event_txtNameKeyReleased

    private void txtEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyReleased
        // TODO add your handling code here:
        if (!usernamePatternCorrect(txtEmail.getText()) && !(txtEmail.getText().isEmpty()) && system.getCustomerDirectory().checkIfUsernameIsUnique(txtEmail.getText())){
              emailLbl.setVisible(true);
              emailIDAlreadyLbl.setVisible(false);
              emailSuccessLbl.setVisible(false);
              emailValid =false;
        }else if(txtEmail.getText().isEmpty()){
            emailLbl.setVisible(false);
            emailIDAlreadyLbl.setVisible(false);
            emailValid =false;
             emailSuccessLbl.setVisible(false);
        }else if(!system.getCustomerDirectory().checkIfUsernameIsUnique(txtEmail.getText())){
            emailIDAlreadyLbl.setVisible(true);
            emailSuccessLbl.setVisible(false);
            emailValid =false;
        }else{
         emailLbl.setVisible(false);
         emailIDAlreadyLbl.setVisible(false);
         emailSuccessLbl.setVisible(true);
         emailValid =true;
        }
    }//GEN-LAST:event_txtEmailKeyReleased

    private void txtPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyReleased
        // TODO add your handling code here:
        if(!passwordPatternCorrect(txtPassword.getText()) && !(txtPassword.getText().isEmpty())){
            passwordSuccessLbl.setVisible(false);
            passwordLbl.setVisible(true);
        }else if(txtPassword.getText().isEmpty()){
            passwordLbl.setVisible(false);
             passwordSuccessLbl.setVisible(false);
        }else{
            passwordLbl.setVisible(false);
            passwordSuccessLbl.setVisible(true);
        }
    }//GEN-LAST:event_txtPasswordKeyReleased

    private void txtAdressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAdressKeyReleased
        // TODO add your handling code here:
        if(!addressPatternCorrect(txtAdress.getText()) && !(txtAdress.getText().isEmpty())){
            addressSuccessLbl.setVisible(false);
            addressLbl.setVisible(true);
        }else if(txtAdress.getText().isEmpty()){
            addressLbl.setVisible(false);
             addressSuccessLbl.setVisible(false);
        }else{
            addressLbl.setVisible(false);
            addressSuccessLbl.setVisible(true);
        }
    }//GEN-LAST:event_txtAdressKeyReleased

    private void txtCityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCityKeyReleased
        // TODO add your handling code here:
        if(!cityPatternCorrect(txtCity.getText()) && !(txtCity.getText().isEmpty())){
            citySuccessLbl.setVisible(false);
            cityLbl.setVisible(true);
            cityValid = false;
        }else if(txtCity.getText().isEmpty()){
            citySuccessLbl.setVisible(false);
            cityLbl.setVisible(false);
            cityValid = false;
        }else{
            cityValid = true;
            cityLbl.setVisible(false);
            citySuccessLbl.setVisible(true);
        }
    }//GEN-LAST:event_txtCityKeyReleased

    private void txtZipcodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtZipcodeKeyReleased
        // TODO add your handling code here:
        int zip=0;
        try{
            zip = Integer.parseInt(txtZipcode.getText());
            if(zip == 0){
                zipLbl.setVisible(false);
                zipSuccessLbl.setVisible(false);
                zipValid = false;
            }
            zipValid = true;
             zipSuccessLbl.setVisible(true);
             zipLbl.setVisible(false);
             return;
        }catch(NumberFormatException e){
            if(!txtZipcode.getText().isEmpty()){
             zipValid = false;
             zipSuccessLbl.setVisible(false);
             zipLbl.setVisible(true);
             return;
            }else {
             zipValid = false;
             zipLbl.setVisible(false);
             zipSuccessLbl.setVisible(false);
             return;
            }
        }
    }//GEN-LAST:event_txtZipcodeKeyReleased

    private void txtHeightKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHeightKeyReleased
        // TODO add your handling code here:
        int height=0;
        if(txtHeight.getText().isEmpty()){
        heightSuccessLbl.setVisible(false);
             heightLbl.setVisible(false);
        }
        try{
            height = Integer.parseInt(txtHeight.getText());
        }catch(NumberFormatException e){
            if(!txtHeight.getText().isEmpty()){
             heightValid = false;
             heightSuccessLbl.setVisible(false);
             heightLbl.setVisible(true);
             return;
            }else {
             heightValid = false;
             heightLbl.setVisible(false);
             heightSuccessLbl.setVisible(false);
             return;
            }
        }
        if(txtHeight.getText().length() > 3 || txtHeight.getText().length() < 3){
            heightValid = false;
             heightLbl.setVisible(true);
             heightSuccessLbl.setVisible(false);
        }else{
             heightValid = true;
             heightLbl.setVisible(false);
             heightSuccessLbl.setVisible(true);
        }
    }//GEN-LAST:event_txtHeightKeyReleased

    private void txtWeightKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtWeightKeyReleased
        // TODO add your handling code here:
        int weight=0;
        if(txtWeight.getText().isEmpty()){
        weightSuccessLbl.setVisible(false);
             weightLbl.setVisible(false);
        }
        try{
            weight = Integer.parseInt(txtWeight.getText());
        }catch(NumberFormatException e){
            if(!txtWeight.getText().isEmpty()){
             weightValid = false;
             weightSuccessLbl.setVisible(false);
             weightLbl.setVisible(true);
             return;
            }else {
             weightValid = false;
             weightLbl.setVisible(false);
             weightSuccessLbl.setVisible(false);
             return;
            }
        }
        if(weight > 200){
            weightValid = false;
            weightLbl.setVisible(true);
            weightSuccessLbl.setVisible(false);
        }else{
             weightValid = true;
             weightLbl.setVisible(false);
             weightSuccessLbl.setVisible(true);
        }
    }//GEN-LAST:event_txtWeightKeyReleased

    private void txtWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWeightActionPerformed

    private void txtCityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCityKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityKeyPressed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgeSuccessLbl;
    private javax.swing.JLabel addressLbl;
    private javax.swing.JLabel addressSuccessLbl;
    private javax.swing.JLabel ageBandLbl;
    private javax.swing.JLabel bgLbl;
    private javax.swing.JCheckBox cholestrolChkBox;
    private javax.swing.JLabel cityLbl;
    private javax.swing.JLabel citySuccessLbl;
    private javax.swing.JLabel confirmPasswordLbl;
    private javax.swing.JLabel confirmPasswordSuccessLbl;
    private javax.swing.JPasswordField confirmPasswordTxt;
    private javax.swing.JCheckBox diabetesChkBox;
    private javax.swing.JLabel emailIDAlreadyLbl;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JLabel emailSuccessLbl;
    private javax.swing.JLabel heightLbl;
    private javax.swing.JLabel heightSuccessLbl;
    private javax.swing.JCheckBox hyperChkBox;
    private javax.swing.JLabel invalidAgeLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JLabel nameSuccessLbl;
    private javax.swing.JComboBox networkJComboBox;
    private javax.swing.JCheckBox noneChkBox;
    private javax.swing.JLabel passwordLbl;
    private javax.swing.JLabel passwordSuccessLbl;
    private javax.swing.JCheckBox pcosChkBox;
    private javax.swing.JRadioButton radioFemale;
    private javax.swing.JRadioButton radioMale;
    private javax.swing.JButton resetBtn;
    private javax.swing.JButton submitBtn;
    private javax.swing.JCheckBox thyroidChkBox;
    private javax.swing.JTextField txtAdress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtWeight;
    private javax.swing.JTextField txtZipcode;
    private javax.swing.JLabel weightLbl;
    private javax.swing.JLabel weightSuccessLbl;
    private javax.swing.JLabel zipLbl;
    private javax.swing.JLabel zipSuccessLbl;
    // End of variables declaration//GEN-END:variables
}
